execution:
- executor: jmeter
  scenario: CreateUser
  iterations: 10
  concurrency: 1

scenarios:
  CreateUser:
    follow-redirects: true
    data-sources:
    - path: users.csv
      variable-names: emailAddress,firstName,lastName,postalCode
    variables:
      BASE_URL: http://vagrant:8080/bank
    requests:
      - url: '${BASE_URL}/api/v1/auth?username=admin@demo.io&password=Demo123!'
        method: POST
        label: 1. Authenticate API User
        headers:
          Content-Type: application/json
        assert:
         - contains:
           - '200'
           subject: http-code
           regexp: true
           assume-success: true
        extract-jsonpath:
          authToken: 'authToken'
      - url: '${BASE_URL}/api/v1/user?role=USER'
        method: POST
        label: 2. Create User
        headers:
          Authorization: Bearer ${authToken}
          Content-Type: application/json
        body: '{ "address": "HC-03 BOX 20665", "country": "US", "dob": "01/11/1923", "emailAddress": "${emailAddress}", "firstName": "${firstName}", "gender": "F", "homePhone": "7731418718", "lastName": "${lastName}", "locality": "Austin", "mobilePhone": "7731418718", "password": "Demo123!", "postalCode": "${postalCode}", "region": "AR", "ssn": "${__Random(100000000,999999999)}", "title": "Mr.", "workPhone": "7731418718" }'
        assert:
         - contains:
           - '201'
           subject: http-code
           regexp: true
           assume-success: true

